version: "3"
services:
  #   mongodb:
  #     image: mongo
  #     volumes:
  #       - data:/data/configdb
  #       - data:/data/db
  #     ports:
  #       - 27018:27017
  dzcot:
    image: dev-llvm
    build:
      cache_from:
        - dev-llvm
      context: ../dev-llvm
    depends_on:
      - mongodb
    environment:
      - PROJECT_PATH=node-dzcot
      - INIT_FILE=init.sh
      - WAIT_SEC=2
      - TZ=
      - DB_NAME=${DB_NAME:-dzcot}
      - DB_PASSWORD=${DB_PASSWORD:-SimplePassword123}
    volumes:
      - type: bind
        source: ${GIT_CONFIG_PATH:-~/.gitconfig}
        target: /home/user/.gitconfig
        read_only: true
      - type: bind
        source: ${SSH_PATH:-~/.ssh}
        target: /home/user/.ssh
        read_only: true
      - type: bind
        source: ${BASH_ALIASES_PATH:-../res/.bash_aliases}
        target: /home/user/.bash_aliases
        read_only: true
      - type: bind
        source: ${BASH_ALIASES_PATH:-../res/.bash_aliases}
        target: /root/.bash_aliases
        read_only: true
      - home:/home/user:delegated
      - ../..:/opt/workspace/node-dzcot:cached
    # ports:
    #   - 9000:9000
volumes:
  #   data:
  #     driver_opts:
  #       type: tmpfs
  #       device: tmpfs
  home:
